/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, regenerate it:
 * npm run generate:types
 */

export interface Config {
  collections: {
    users: User
    media: Media
    projects: Project
    posts: Post
    exhibits: Exhibit
  }
  globals: {}
}

export interface User {
  id: string
  email: string
  name?: string | null
  role?: ('admin' | 'editor') | null
  updatedAt: string
  createdAt: string
}

export interface Media {
  id: string
  alt?: string | null
  caption?: string | null
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
  updatedAt: string
  createdAt: string
}

export interface Project {
  id: string
  title: string
  slug: string
  description?: string | null
  coverImage?: (string | Media) | null
  status?: ('draft' | 'published') | null
  publishedAt?: string | null
  layout?: (HeroBlock | GalleryBlock | TextBlock | ImageTextBlock | QuoteBlock | SpacerBlock)[] | null
  updatedAt: string
  createdAt: string
}

export interface Post {
  id: string
  title: string
  slug: string
  type?: ('essay' | 'short') | null
  excerpt?: string | null
  content?: {
    root: {
      type: string
      children: {
        type: string
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  featuredImage?: (string | Media) | null
  status?: ('draft' | 'published') | null
  publishedAt?: string | null
  tags?: string[] | null
  updatedAt: string
  createdAt: string
}

export interface Exhibit {
  id: string
  title: string
  slug: string
  description?: string | null
  location?: string | null
  startDate?: string | null
  endDate?: string | null
  coverImage?: (string | Media) | null
  status?: ('upcoming' | 'current' | 'past') | null
  layout?: (HeroBlock | GalleryBlock | TextBlock | ImageTextBlock | QuoteBlock | SpacerBlock)[] | null
  updatedAt: string
  createdAt: string
}

export interface HeroBlock {
  blockType: 'hero'
  heading?: string | null
  subheading?: string | null
  image: string | Media
  overlayOpacity?: number | null
  height?: ('full' | 'large' | 'medium' | 'small') | null
}

export interface GalleryBlock {
  blockType: 'gallery'
  photoSource: 'existing' | 'payload'
  projectId?: string | null
  images?: {
    image: string | Media
    id?: string | null
  }[] | null
  layout?: ('grid' | 'masonry' | 'carousel' | 'single') | null
  columns?: ('2' | '3' | '4') | null
  showCaptions?: boolean | null
  enableLightbox?: boolean | null
}

export interface TextBlock {
  blockType: 'text'
  content: {
    root: {
      type: string
      children: {
        type: string
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  }
  alignment?: ('left' | 'center' | 'right') | null
  maxWidth?: ('full' | 'large' | 'medium' | 'small') | null
}

export interface ImageTextBlock {
  blockType: 'imageText'
  image: string | Media
  content: {
    root: {
      type: string
      children: {
        type: string
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  }
  imagePosition?: ('left' | 'right') | null
  imageSize?: ('small' | 'medium' | 'large') | null
  verticalAlignment?: ('top' | 'center' | 'bottom') | null
}

export interface QuoteBlock {
  blockType: 'quote'
  quote: string
  attribution?: string | null
  style?: ('default' | 'large' | 'minimal') | null
}

export interface SpacerBlock {
  blockType: 'spacer'
  size: 'xs' | 'sm' | 'md' | 'lg' | 'xl'
}
